services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-integracao-api
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATA_BASE_URL: mongodb://mongodb:27017/desafio-integracao
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: desafio-integracao-mongodb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
